NotenWeb/Models/Sheet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NotenWeb.Models
{
    /// <summary>
    /// Sheet Model. Price, Duration and Orchestra-Infos are converted in the SheetVM!
    /// Therefore here no Properties!
    /// </summary>
    public class Sheet
    {
        // Attributes are in fluent API in NotenvDbContext: MaxLength
        public int Id { get; set; }

        // Converted in SheetVM
        public int? OrchestraId { get; set; }

        [Display(Name = "Nr")]
        [Range(1,100000,
            ErrorMessage = "Inventarnummer muss zwischen 1 und 100.000 liegen.")]
        public int? InventoryNumber { get; set; }

        [Display(Name = "Titel")]
        [RegularExpression(@"[A-Za-z0-9.,:_#'~+\-\*äöüÄÖÜ<>|^°!""§$%&/()=?{[\]}\\#\s]*", 
            ErrorMessage = "Kein Semikolon (Strichpunkt) erlaubt")]
        public string Title { get; set; }

        [Display(Name = "Komponist")]
        [RegularExpression(@"[A-Za-z0-9.,:_#'~+\-\*äöüÄÖÜ<>|^°!""§$%&/()=?{[\]}\\#\s]*",
            ErrorMessage = "Kein Semikolon (Strichpunkt) erlaubt")]
        public string Composer { get; set; }

        //Composer is not used, Arrangeur as combi-field for Arrangeur / Composer
        [Display(Name = "Arrangeur / Komponist")]
        [RegularExpression(@"[A-Za-z0-9.,:_#'~+\-\*äöüÄÖÜ<>|^°!""§$%&/()=?{[\]}\\#\s]*",
            ErrorMessage = "Kein Semikolon (Strichpunkt) erlaubt")]
        public string Arrangeur { get; set; }

        [Display(Name = "Schwierigkeit")]
        public int? Difficulty { get; set; }

        [Display(Name = "Partitur")]
        [RegularExpression(@"[A-Za-z0-9.,:_#'~+\-\*äöüÄÖÜ<>|^°!""§$%&/()=?{[\]}\\#\s]*",
            ErrorMessage = "Kein Semikolon (Strichpunkt) erlaubt")]
        public string Score { get; set; }

        // Converted in SheetVM
        public int? Duration { get; set; }

        // Converted in SheetVM
        public int? Price { get; set; }

        [Display(Name = "Ausgeliehen")]
        [RegularExpression(@"[A-Za-z0-9.,:_#'~+\-\*äöüÄÖÜ<>|^°!""§$%&/()=?{[\]}\\#\s]*",
            ErrorMessage = "Kein Semikolon (Strichpunkt) erlaubt")]
        public string LendTo { get; set; }

        [Display(Name = "Notizen")]
        [RegularExpression(@"[A-Za-z0-9.,:_#'~+\-\*äöüÄÖÜ<>|^°!""§$%&/()=?{[\]}\\#\s]*",
            ErrorMessage = "Kein Semikolon (Strichpunkt) erlaubt")]
        public string Notes { get; set; }
    }
}

NotenWeb/Controllers/SheetsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NotenWeb.Models;
using NotenWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


/// <summary>
/// Sheets Controller for IndexSheets and CRUD operations
/// </summary>

namespace NotenWeb.Controllers
{
    public class SheetsController : Controller
    {
        #region Fields
        protected NotenvDbContext _context;

        // used to generate the VM of the Sheets with orchestra names
        private List<Orchestra> _listOrchestras;

        #endregion


        /// <summary>
        /// Constructor of Sheets Controller, which also gets new DbContext
        /// this is called the constructor injector and this works, because 
        /// NotenvDbContext is added as service in startup - configure  service
        /// </summary>
        /// <param name="context">Database Context</param>

        public SheetsController(NotenvDbContext context)
        {
            _context = context;
            _listOrchestras = _context.Orchestra.OrderBy(o => o.OrderNr).ToList();
        }



        /// <summary>
        /// GET /Sheets/IndexSheets/(optional: ?SearchString=Tequila )
        /// Note: ?SearchString=Tequila can be appended and is bound to parameter string SearchString. 
        /// 
        /// Note: SearchString and SelOrchestra are submitted by asp-for and method = get. This makes
        /// - binding to VM (asp-for)
        /// - url-parameter (get)
        /// without asp-for and just "name"-tag the url-parameter stays, but the searchstring is not retained at page
        /// 
        /// main page of sheets with table. 
        /// Only for Authorized Users
        /// </summary>

        [Authorize(Roles = "Admins,ReadOnlyUser,PowerUser")]
        public async Task<IActionResult> IndexSheets(string SelOrchestra, string SearchString)
        {
            // Note: Query is only defined. Nothing is done in database yet.
            // No Sheets from recycler
            var sheets = _context.Sheet.Where(s => s.OrchestraId != -2)
                                       .OrderBy(s => s.OrchestraId).ThenBy(s => s.InventoryNumber)
                                       .Select(s => s);



            // Get List of Orchestras
            var orchestras = from o in _context.Orchestra
                        orderby o.OrderNr
						select o;

						
			// Check if user has write-access
			bool write = false;
			if (User.IsInRole("Admins") | User.IsInRole("PowerUser") )
				write = true;
			
	
	
			// Filter sheets for SearchString (no SheetVM necessary)
            if (!string.IsNullOrEmpty(SearchString))
            {
                // Note: query execution is deferred. 
                // That means that the evaluation of an expression is delayed 
                // until its realized value is actually iterated over or the 
                // ToListAsync method is called.
                sheets = sheets.Where(s => s.Title.Contains(SearchString));
            }

            // Filter sheets for Orchestra. 
            // All: string=-1. Archive: string="0". options added in View. 
            // Other Orchestras compared with string-values. ; and & are ok

			if (!string.IsNullOrEmpty(SelOrchestra))
			{
				// find Orchestra ID of selected orchestra
				int SelID = -1;
				if(SelOrchestra == "0")
					SelID = 0;
				
				foreach (Orchestra o in orchestras)
				{
					if (o.Label == SelOrchestra)
					{
						SelID = o.Id;
						break;
					}
				}
				
				// only when Orchestra Filter selected
				if ( SelID > -1)
					sheets = sheets.Where(s => s.OrchestraId == SelID); 
				
			}
			
			
            // executes query on database
            var SheetModelList = await sheets.ToListAsync();


            // Build List of SheetVM here in the controller
            List<SheetVM> ControllerSheetVMs = new List<SheetVM>();

            foreach (Sheet SheetModel in SheetModelList)
            {
                SheetVM svm = new SheetVM(SheetModel, ref _listOrchestras);
                ControllerSheetVMs.Add(svm);
            }

            // Build SheetsOrchestrasVM;
            // use LINQ to get list of Orchestras
            //Note: SelectLists compare for strings.
            //Options Archive(string-value 0) and All(string value -1) are added in view.

            IQueryable<string> orchQuery = from o in orchestras
                                            select o.Label;

            var sovm = new SheetsOrchestrasVM
			{
				SheetVMs = ControllerSheetVMs,
				SelListOrchestras = new SelectList(orchQuery), // Archive and All added in View
				WriteAccess = write // hiding links in IndexSheets
			};
            
            return View(sovm);
        }



        /// <summary>
        /// GET: /Sheets/Details/5
        /// Only for Authorized Users
        /// As Details shows price and duration, these have to be converted (int in database)
        /// therefore SheetVM is generated
        /// Shows Details for one sheet
        /// </summary>
        /// <param name="id">Sheet Id for which details shall be shown</param>
        /// <returns></returns>

        [Authorize(Roles = "Admins,ReadOnlyUser,PowerUser")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sheet = await _context.Sheet
                .SingleOrDefaultAsync(m => m.Id == id);
            if (sheet == null)
            {
                return NotFound();
            }

			// Check if user has write-access
			bool write = false;
			if (User.IsInRole("Admins") | User.IsInRole("PowerUser") )
				write = true;
			
			
            // convert price and duration, generate VM
            SheetVM svm = new SheetVM(sheet, ref _listOrchestras);
			svm.WriteAccess = write; // hiding "Edit"

            return View(svm);
        }



        /// <summary>
        /// GET: /Sheets/Create
        /// Empty SheetVM can't be created automatically, because list of orchestras have to be generated
        /// Note: Write-Access in SheetVM = false, but this is not considered
        /// 
        /// Only for Authorized Users (Admins and PowerUsers)
        /// </summary>

        [Authorize(Roles = "Admins,PowerUser")]
        public IActionResult Create()
        {

            // Empty, only list of Orchestras for SelectList
            SheetVM svm = new SheetVM(ref _listOrchestras);
            
            return View(svm);
        }




        /// <summary>
        /// POST /Sheets/Create 
        /// can be invoked only for POST requests
        /// converts SheetViewModel to sheet (Price and Duration)
        /// tries to create a new sheet --> This calls parameterless SheetVM constructor
        /// </summary>
        /// <param name="sheetVM"></param>
        /// <returns></returns>
        
        [Authorize(Roles = "Admins,PowerUser")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            //[Bind("SheetModel,OrchestraName,Duration,Price")] // Binding Property not necessary as no overposting possible
            // This means no secret property. And Id is checked.
            SheetVM sheetVM)
        {
            if (ModelState.IsValid)
            {
                // convert sheetVM back to sheet (price, duration, OrchestraId)

                bool found = sheetVM.ConvertBack(ref _listOrchestras);

                //----------!!!----------- DEBUG
                if (!found)
                    Console.WriteLine("\n----- Orchestra string was not found. SheetsController -> ConvertBack");

                _context.Add(sheetVM.SheetModel);
                await _context.SaveChangesAsync();
                return RedirectToAction("IndexSheets");
            }
            
            // if model is not valid / validation fails: show same page
            return View(sheetVM);
        }

        

        /// <summary>
        /// GET: /Sheets/Edit/5
        /// Only for Authorized Users (Admins and PowerUsers)
        /// As Edit shows price and duration, these have to be converted (int in database)
        /// Shows Edit for one sheet
        /// </summary>
        /// <param name="id">Sheet Id for the Sheet to be Edited</param>
        /// <returns></returns>

        [Authorize(Roles = "Admins,PowerUser")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sheet = await _context.Sheet.SingleOrDefaultAsync(m => m.Id == id);
            if (sheet == null)
            {
                return NotFound();
            }

            // convert price and duration, generate VM
            SheetVM svm = new SheetVM(sheet, ref _listOrchestras);

            return View(svm);
        }



        /// <summary>
        /// POST: /Sheets/Edit/5
        /// Only for Authorized Users (Admins and PowerUsers)
        /// As Edit shows price and duration, these have to be converted (int in database)
        /// Saves the edited sheet
        /// </summary>
        /// <param name="id">Sheet Id for the Sheet to be Edited</param>
        /// <param name="sheetVM">New Sheet Information</param>
        /// <returns></returns>

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [Authorize(Roles = "Admins,PowerUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            //[Bind("SheetModel,OrchestraName,Duration,Price")] // Binding Property not necessary as no overposting possible

NotenWeb/Views/Sheets/Create.cshtml
@model NotenWeb.ViewModels.SheetVM

@{
    ViewData["Title"] = "Stück erstellen";
}

<h2>Stücke - Erstellen</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>


        @*This was text-field for OrchestraName*@
        @*<div class="form-group">
            <label asp-for="OrchestraName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="OrchestraName" class="form-control" />
                <span asp-validation-for="OrchestraName" class="text-danger"></span>
            </div>
        </div>*@

        @*Note: SelectLists compare for strings.
        Options Archive (string-value 0) and All (string value -1) are added in view.*@

        @*SlectList for OrchestraName. Labels are used, string-comares*@
        <div class="form-group">
            <label asp-for="OrchestraName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="OrchestraName" asp-items="Model.SelListOrchestras">
                    <option value="0">Archiv</option>
                </select>
                <span asp-validation-for="OrchestraName" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <label asp-for="SheetModel.InventoryNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SheetModel.InventoryNumber" class="form-control" />
                <span asp-validation-for="SheetModel.InventoryNumber" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="SheetModel.Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SheetModel.Title" class="form-control" />
                <span asp-validation-for="SheetModel.Title" class="text-danger"></span>
            </div>
        </div>

        @*Composer is not used, Arrangeur as combi-field for Arrangeur / Composer*@
        @*<div class="form-group">
            <label asp-for="SheetModel.Composer" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SheetModel.Composer" class="form-control" />
                <span asp-validation-for="SheetModel.Composer" class="text-danger"></span>
            </div>
        </div>*@

        @*Composer is not used, Arrangeur as combi-field for Arrangeur / Composer*@
        <div class="form-group">
            <label asp-for="SheetModel.Arrangeur" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SheetModel.Arrangeur" class="form-control" />
                <span asp-validation-for="SheetModel.Arrangeur" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="SheetModel.Difficulty" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SheetModel.Difficulty" class="form-control" />
                <span asp-validation-for="SheetModel.Difficulty" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="SheetModel.Score" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SheetModel.Score" class="form-control" />
                <span asp-validation-for="SheetModel.Score" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Duration" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="SheetModel.LendTo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SheetModel.LendTo" class="form-control" />
                <span asp-validation-for="SheetModel.LendTo" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="SheetModel.Notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SheetModel.Notes" class="form-control" />
                <span asp-validation-for="SheetModel.Notes" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Erstellen" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div class="back-to-list">
    <a asp-action="IndexSheets">Zurück zur Liste</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

NotenWeb/Views/Sheets/Delete.cshtml
@model NotenWeb.ViewModels.SheetVM

@{
    ViewData["Title"] = "Löschen";
}

<h2>Stücke - Löschen</h2>

<h3>Bist du sicher, dass du dieses Stück löschen willst?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrchestraName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrchestraName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.InventoryNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.InventoryNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Title)
        </dd>
        @*Composer is not used, Arrangeur as combi-field for Arrangeur / Composer*@
        @*<dt>
            @Html.DisplayNameFor(model => model.SheetModel.Composer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Composer)
        </dd>*@
        @*Composer is not used, Arrangeur as combi-field for Arrangeur / Composer*@
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.Arrangeur)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Arrangeur)
        </dd>
    </dl>


    <form asp-action="Delete">
        <div class="form-actions no-color delete-button">
            <input type="submit" value="Löschen" class="btn btn-default" />
        </div>
    </form>

    <div class="back-to-list">
        <a asp-action="IndexSheets">Zurück zur Liste</a>
    </div>
 
</div>

NotenWeb/Views/Sheets/Details.cshtml
@model NotenWeb.ViewModels.SheetVM

@{
    ViewData["Title"] = "Details";
}

<h2>Stücke - Details</h2>


<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrchestraName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrchestraName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.InventoryNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.InventoryNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Title)
        </dd>
        @*Composer is not used, Arrangeur as combi-field for Arrangeur / Composer*@
        @*<dt>
            @Html.DisplayNameFor(model => model.SheetModel.Composer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Composer)
        </dd>*@
        @*Composer is not used, Arrangeur as combi-field for Arrangeur / Composer*@
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.Arrangeur)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Arrangeur)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.Difficulty)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Difficulty)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.Score)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Score)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.LendTo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.LendTo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SheetModel.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SheetModel.Notes)
        </dd>
    </dl>
</div>

<div>
    @if (Model.WriteAccess)
    {
        <div class="edit-link">
            <a asp-action="Edit" asp-route-id="@Model.SheetModel.Id">Edit</a>
        </div>
    }

    <div class="back-to-list">
        <a asp-action="IndexSheets">Zurück zur Liste</a>
    </div>

</div>

NotenWeb/Views/Sheets/IndexSheets.cshtml
@model NotenWeb.ViewModels.SheetsOrchestrasVM

@{
    ViewData["Title"] = "Stücke";
}

<h2>Stücke</h2>

@*ADD*@
@if (Model.WriteAccess)
{
    <div class="create-link">
        <a asp-action="Create">Hinzufügen</a>
    </div>
}

@*SEARCH*@

@*SearchString and SelOrchestra are submitted by asp-for and method = get. This makes
        - binding to VM (asp-for)
        - url-parameter (get)
          without asp-for and just "name"-tag the url-parameter stays, but the searchstring is not retained at page*@

        @*Note: SelectLists compare for strings. 
        Options Archive (string-value 0) and All (string value -1) are added in view.*@

<form asp-controller="Sheets" asp-action="IndexSheets" method="get">
    <div class="search-block">
        <select asp-for="SelOrchestra" asp-items="Model.SelListOrchestras">
            <option value="-1">Alle</option>
            <option value="0">Archiv</option>
        </select>


        @Html.DisplayNameFor(Model => Model.SheetVMs[0].SheetModel.Title): <input type="text" asp-for="SearchString">
        <input type="submit" value="Suchen" />
    </div>
</form>

@*TABLE*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(Model => Model.SheetVMs[0].OrchestraName)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.SheetVMs[0].SheetModel.InventoryNumber)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.SheetVMs[0].SheetModel.Title)
            </th>
            @*Composer is not used, Arrangeur as combi-field for Arrangeur / Composer*@
            @*<th>
                @Html.DisplayNameFor(Model => Model.SheetVMs[0].SheetModel.Composer)
            </th>*@
            <th>
                @Html.DisplayNameFor(Model => Model.SheetVMs[0].SheetModel.Arrangeur)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.SheetVMs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrchestraName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SheetModel.InventoryNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SheetModel.Title)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.SheetModel.Composer)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.SheetModel.Arrangeur)
                </td>
                <td>
                    @if (Model.WriteAccess)
                    {
                        <a asp-controller="Sheets" asp-action="Edit" asp-route-id="@item.SheetModel.Id">Edit</a><text> | </text>
                    }

                    <a asp-controller="Sheets" asp-action="Details" asp-route-id="@item.SheetModel.Id">Details</a>

                    @if (Model.WriteAccess)
                    {
                        <text> | </text><a asp-controller="Sheets" asp-action="Delete" asp-route-id="@item.SheetModel.Id">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>