NotenWeb/Controllers/RoundsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NotenWeb.Models;
using NotenWeb.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;


/// <summary>
/// Rounds Controller for IndexRounds
/// Note: no CRUD. No edit supported in WebApp
/// </summary>

namespace NotenWeb.Controllers
{
    public class RoundsController : Controller
    {
        #region Fields
        protected NotenvDbContext _context;

        #endregion


        /// <summary>
        /// Constructor of Rounds Controller, which also gets new DbContext
        /// this is called the constructor injector and this works, because 
        /// NotenvDbContext is added as service in startup - configure  service
        /// 
        /// Note: Sheets use a ViewModel because of Price, Duration and WriteAccess. 
        /// And the IndexSheets uses another VM for search.
        /// Rounds use also VM because RoundGroups
        /// </summary>
        /// <param name="context">Database Context</param>

        public RoundsController(NotenvDbContext context)
        {
            _context = context;
        }



        /// <summary>
        /// GET /Rounds/IndexRounds
        /// main page of Rounds with table. 
        /// Only for Authorized Users
        /// </summary>

        [Authorize(Roles = "Admins,ReadOnlyUser,PowerUser")]
        public async Task<IActionResult> IndexRounds()
        {
			// Note: Try to use Sheets without SheetVM, because they also need Orchestras.
			// Orchestra, Price, Duration,... doesn't matter here.
			
			List<Sheet> SheetModelList = await _context.Sheet.ToListAsync();
			List<Round> RoundModelList = await _context.Round.ToListAsync();
			
			List<RoundGroupVM> RoundGroupVMs = new List<RoundGroupVM>();
			
			for(int n = 0; n < RoundModelList.Count; n++)
            {
                RoundVM rvm = new RoundVM(RoundModelList[n], ref SheetModelList);

                if (n==0) //first element: Make first Roundgroup
                {
                    RoundGroupVMs.Add(new RoundGroupVM(rvm.RoundModel.Roundgroup)); //generate roundgroup with first label and add it to collection
                }

                bool RoundGroupAlreadyExists = false;
                foreach (RoundGroupVM rgvm in RoundGroupVMs)
                {
                    if(rvm.RoundModel.Roundgroup == rgvm.RoundGroupLabel)
                    {
                        rgvm.AddRound(rvm);
                        RoundGroupAlreadyExists = true;
                    }
                }

                if (!RoundGroupAlreadyExists)
                {
                    RoundGroupVM rgvm = new RoundGroupVM(rvm.RoundModel.Roundgroup);
                    rgvm.AddRound(rvm);
                    
                    RoundGroupVMs.Add(rgvm);
                }
            }

            //sort all
            foreach(RoundGroupVM rgvm in RoundGroupVMs)
            {
                rgvm.SortRounds();
            }
			
			
			
			
			
			return View(RoundGroupVMs);
        }




    }
}

NotenWeb/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NotenWeb.Models;
using NotenWeb.ViewModels;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;


/// <summary>
/// Users Controller for IndexUsers and Add / Delete (no edit)
/// </summary>

namespace NotenWeb.Controllers
{
    public class UsersController : Controller
    {
        #region Fields
        protected NotenvDbContext _context;

		// Manager for User Creation, Deletion ...
        protected UserManager<AppUsers> _userManager;
		
		// Manager for roles
        protected RoleManager<IdentityRole> _roleManager;
		
        #endregion


        /// <summary>
        /// Constructor of Users Controller, which also gets new DbContext
        /// this is called the constructor injector and this works, because NotenvDbContext is added as service in startup - configure  service
        /// </summary>
        /// <param name="context">Database Context</param>
        /// <param name="userManager">User Manager</param>
        /// <param name="roleManager">Role Manager</param>

		public UsersController(
            NotenvDbContext context,
            UserManager<AppUsers> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }



        /// <summary>
        /// GET /Users/IndexUsers
        /// main page of Users with table. 
		/// Note: Users have a UsersVM, which has bool-variables for the role
        /// Only for Admins
        /// </summary>

        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> IndexUsers()
        {
			// Get List of all Users
			List<AppUsers> AllUsers = await _userManager.Users.ToListAsync();


			// Generate List of UserVMs
			List<UserVM> UserVMs = new List<UserVM>();
			
			foreach (AppUsers user in AllUsers)
			{
				UserVM uVM = new UserVM(user, _userManager);
				UserVMs.Add(uVM);
			}
		
			return View(UserVMs);
        }
		
		
		
		/// <summary>
        /// POST /Users/CreateRoles
        /// can be invoked only for POST requests
        /// tries to create the Roles Admin, PowerUser and ReadOnlyUser (initially necessary and without Admin Deadlock)
        /// </summary>
        /// <returns></returns>
        
        [Authorize(Roles = "Admins")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRoles()
        {
            string returnstring = "";
            // Create all Roles if not existent
            bool x = await _roleManager.RoleExistsAsync("Admins");
            if (x)
			{
				returnstring += "Rolle Admins existiert bereits \n";
			}
			else
            {
                var role = new IdentityRole();
                role.Name = "Admins";
                await _roleManager.CreateAsync(role);

                returnstring += "Rolle Admins war nicht da, wurde erzeugt \n";
            }

            x = await _roleManager.RoleExistsAsync("ReadOnlyUser");
            if (x)
			{
				returnstring += "Rolle ReadOnlyUser existiert bereits \n";
			}
			else
            {
                var role = new IdentityRole();
                role.Name = "ReadOnlyUser";
                await _roleManager.CreateAsync(role);

                returnstring += "Rolle ReadOnlyUsers war nicht da, wurde erzeugt \n";
            }

            x = await _roleManager.RoleExistsAsync("PowerUser");
            if (x)
			{
				returnstring += "Rolle PowerUser existiert bereits \n";
			}
			else
            {
                var role = new IdentityRole();
                role.Name = "PowerUser";
                await _roleManager.CreateAsync(role);

                returnstring += "Rolle PowerUsers war nicht da, wurde erzeugt \n";
            }
            return Content(returnstring, "text/html");
        }
		
		
		
		
		/// <summary>
        /// GET: /Users/Create
        /// Only for Authorized Users (Admins)
        /// </summary>

        [Authorize(Roles = "Admins")]
        public IActionResult Create()
        {
            return View();
        }



        /// <summary>
        /// POST /Users/Create 
        /// can be invoked only for POST requests
        /// tries to create a new User
        /// </summary>
        /// <param name="userVM"></param>
        /// <returns></returns>
        
        [Authorize(Roles = "Admins")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserVM uvm)
        {
            string returnstring = "Fehler";
			if (ModelState.IsValid)
            {
                // check if only one role is activated
				
				if( (uvm.IsAdmin & uvm.IsPU) | (uvm.IsAdmin & uvm.IsRO) | (uvm.IsPU & uvm.IsRO) )
					return Content("Nur eine Rolle erlaubt! Bitte neu", "text/html");
				
				var user = new AppUsers();
                user.UserName = uvm.UserModel.UserName;

                IdentityResult chkUser = await _userManager.CreateAsync(user, uvm.password);

                // Add New User to correct role   
                if (chkUser.Succeeded)
                {
                    returnstring = "User wurde erfolgreich erzeugt \n";

                    if (uvm.IsAdmin)
                    {
                        IdentityResult result1 = await _userManager.AddToRoleAsync(user, "Admins");
                    }

                    if (uvm.IsPU)
                    {
                        var result1 = await _userManager.AddToRoleAsync(user, "PowerUser");
                    }

                    if (uvm.IsRO)
                    {
                        var result1 = await _userManager.AddToRoleAsync(user, "ReadOnlyUser");
                    }
                }
				
                return Content(returnstring, "text/html");
            }
            
            // if model is not valid / validation fails: show same page
            return View(uvm);
        }
		
		
		
		/// <summary>
        /// GET: /Users/Delete/asdf_USER_id
        /// Only for Authorized Users (Admins)
        /// Show user which shall be deleted
		/// NOTE: UserModel is ok here. no uvm needed.
		
        /// </summary>
        /// <param name="id">user Id for the user to be Deleted</param>

        [Authorize(Roles = "Admins")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.Users
                .SingleOrDefaultAsync(u => u.Id == id);

            if (user == null)
            {
                return NotFound();
            }
			
            return View(user);
        }



        /// POST: /Users/DeleteConfirmed/5
        /// Only for Authorized Users (Admins)
        /// Deletes the User
        /// Note: ActionName("Delete") makes this action accessible in the Delete Form
        /// with id
        /// </summary>
        /// <param name="id">User Id for the user to be Deleted</param>
        /// <returns></returns>

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = "Admins")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _userManager.Users.SingleOrDefaultAsync(u => u.Id == id);
            await _userManager.DeleteAsync(user);
            return RedirectToAction("IndexUsers");
        }


    }
}

NotenWeb/Views/Shared/_AdminLayout.cshtml
@*Layout-File for intern Admin pages*@


@using Microsoft.AspNetCore.Identity
@using NotenWeb.Models
@inject UserManager<AppUsers> UserManager

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] / Admin - NotenWeb</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/Intern/css/normalize.css">
    <link rel="stylesheet" href="~/Intern/css/font-awesome.css">
    <link rel="stylesheet" href="~/Intern/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Intern/css/templatemo-style.css">
</head>



<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    @*This is only visible when width < 992, in Bootstrap.min.css*@

    <div class="responsive-header visible-xs visible-sm">
        <div class="container" id="nav-menue-auf">
            @*nav-menue-auf ist das ziel für target (toggle-menu ohne js)*@
            <div class="row">
                <div class="col-md-12">
                    <div class="top-section">
                        <div class="profile-image">
                            <img src="~/Resources/logo.png" alt="SJK-Logo">
                        </div>
                        <div class="profile-content">
                            <h3 class="profile-title">@UserManager.GetUserAsync(User).Result.UserName </h3>
                            <p class="profile-description">Admin Funktionen</p>
                            <form asp-controller="Account" asp-action="DoLogoutAsync">
                                <fieldset class="logout_button">
                                    <input type="submit" class="button" value="Abmelden">
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            @*make 2 toggle-menu buttons*@
            <a href="#nav-menue-zu" class="toggle-menu toggle-menu-zu"><i class="fa fa-bars"></i></a> @*ZU*@
            <a href="#nav-menue-auf" class="toggle-menu toggle-menu-auf"><i class="fa fa-bars"></i></a> @*AUF*@

            <div class="main-navigation responsive-menu">
                <ul class="navigation">
                    <li><a asp-controller="Sheets" asp-action="IndexSheets">Stücke</a></li>
                    <li><a asp-controller="Orchestras" asp-action="IndexOrchestras">Orchester</a></li>
                    <li><a asp-controller="Rounds" asp-action="IndexRounds">Runden</a></li>
                    <li><a asp-controller="Users" asp-action="IndexUsers">Benutzer</a></li>
                </ul>
            </div>
        </div>
    </div>



    <!-- SIDEBAR -->
    @*This is only visible when width > 992, in Bootstrap.min.css*@
    <div class="sidebar-menu hidden-xs hidden-sm">
        <div class="top-section">
            <div class="profile-image">
                <img src="~/Resources/logo.png" alt="SJK-Logo">
            </div>
            <h3 class="profile-title">@UserManager.GetUserAsync(User).Result.UserName </h3>
            <p class="profile-description">Admin Funktionen</p>
            <form asp-controller="Account" asp-action="DoLogoutAsync">
                <fieldset class="logout_button">
                    <input type="submit" class="button" value="Abmelden">
                </fieldset>
            </form>
        </div> <!-- top-section -->

        <div class="main-navigation">
            <ul class="navigation">
                <li><a asp-controller="Sheets" asp-action="IndexSheets">Stücke</a></li>
                <li><a asp-controller="Orchestras" asp-action="IndexOrchestras">Orchester</a></li>
                <li><a asp-controller="Rounds" asp-action="IndexRounds">Runden</a></li>
                <li><a asp-controller="Users" asp-action="IndexUsers">Benutzer</a></li>
            </ul>
        </div> <!-- .main-navigation -->

    </div> <!-- .sidebar-menu -->
    @*<div class="banner-bg" id="top">
            <div class="banner-overlay"></div>
            <div class="welcome-text">
                <h2>Simple Design | Personal Portfolio</h2>
                <h5>This is a mobile friendly layout with Bootstrap v3.3.1 framework. Maecenas eu ante at nunc posuere fringilla sit amet non dolor. Proin condimentum fermentum nunc.</h5>
            </div>
        </div>*@

    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="fluid-container">

            <div class="content-wrapper">


                @RenderBody()



                <hr>

                <div class="row" id="footer">
                    <div class="col-md-12 text-center">
                        <p class="copyright-text">© DistlerFuchs / V 1.0.00</p>
                    </div>
                </div>

            </div>

        </div>
    </div>

    @*This renders scripts, which are called in views*@
    @RenderSection("Scripts", required: false)

</body>
</html>

NotenWeb/Views/Shared/_ExternLayout.cshtml
@*Layout-File for extern pages (Login, Error)...*@

<!DOCTYPE html>
<html lang="de-de">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Extern/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Extern/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Extern/css/main.css">
    <!--===============================================================================================-->

    <title>@ViewData["Title"] - NotenWeb</title>



</head>

<body>
    <header>
        
        <div id="header_box">
            
            <div id="title_line">
                <h1 class="login100-form-title p-b-33">NotenWeb der SJK</h1>
            </div>
            <div id="logo_box">
                <img id="logo_bild" src="~/Resources/logo.png" alt="Logo für SJK" title="SJK-Logo" />
            </div>

        </div>
    
    </header>

    @RenderBody()


    <footer>
        <p>© DistlerFuchs / V 1.0.00</p>
    </footer>

</body>
</html>

NotenWeb/Views/Shared/_UserLayout.cshtml
@*Layout-File for intern User pages (ReadOnly and PowerUser, both without user settings)*@


@using Microsoft.AspNetCore.Identity
@using NotenWeb.Models
@inject UserManager<AppUsers> UserManager

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - NotenWeb</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/Intern/css/normalize.css">
    <link rel="stylesheet" href="~/Intern/css/font-awesome.css">
    <link rel="stylesheet" href="~/Intern/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Intern/css/templatemo-style.css">
</head>



<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    @*This is only visible when width < 992, in Bootstrap.min.css*@
    
    <div class="responsive-header visible-xs visible-sm">
        <div class="container" id="nav-menue-auf"> @*nav-menue-auf ist das ziel für target (toggle-menu ohne js)*@
            <div class="row">
                <div class="col-md-12">
                    <div class="top-section">
                        <div class="profile-image">
                            <img src="~/Resources/logo.png" alt="SJK-Logo">
                        </div>
                        <div class="profile-content">
                            <h3 class="profile-title">@UserManager.GetUserAsync(User).Result.UserName </h3>
                            <p class="profile-description">Benutzer</p>
                            <form asp-controller="Account" asp-action="DoLogoutAsync">
                                <fieldset class="logout_button">
                                    <input type="submit" class="button" value="Abmelden">
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            @*make 2 toggle-menu buttons*@
            <a href="#nav-menue-zu" class="toggle-menu toggle-menu-zu"><i class="fa fa-bars"></i></a> @*ZU*@
            <a href="#nav-menue-auf" class="toggle-menu toggle-menu-auf"><i class="fa fa-bars"></i></a> @*AUF*@

            <div class="main-navigation responsive-menu" >
                <ul class="navigation">
                    <li><a asp-controller="Sheets" asp-action="IndexSheets">Stücke</a></li>
                    <li><a asp-controller="Orchestras" asp-action="IndexOrchestras">Orchester</a></li>
                    <li><a asp-controller="Rounds" asp-action="IndexRounds">Runden</a></li>
                </ul>
            </div>
        </div>
    </div>


    <!-- SIDEBAR -->
    @*This is only visible when width > 992, in Bootstrap.min.css*@
    <div class="sidebar-menu hidden-xs hidden-sm">
        <div class="top-section">
            <div class="profile-image">
                <img src="~/Resources/logo.png" alt="SJK-Logo">
            </div>
            <h3 class="profile-title">@UserManager.GetUserAsync(User).Result.UserName </h3>
            <p class="profile-description">Benutzer</p>
            <form asp-controller="Account" asp-action="DoLogoutAsync">
                <fieldset class="logout_button">
                    <input type="submit" class="button" value="Abmelden">
                </fieldset>
            </form>
        </div> <!-- top-section -->

        <div class="main-navigation">
            <ul class="navigation">
                <li><a asp-controller="Sheets" asp-action="IndexSheets">Stücke</a></li>
                <li><a asp-controller="Orchestras" asp-action="IndexOrchestras">Orchester</a></li>
                <li><a asp-controller="Rounds" asp-action="IndexRounds">Runden</a></li>
            </ul>
        </div> <!-- .main-navigation -->

    </div> <!-- .sidebar-menu -->
    @*<div class="banner-bg" id="top">
            <div class="banner-overlay"></div>
            <div class="welcome-text">
                <h2>Simple Design | Personal Portfolio</h2>
                <h5>This is a mobile friendly layout with Bootstrap v3.3.1 framework. Maecenas eu ante at nunc posuere fringilla sit amet non dolor. Proin condimentum fermentum nunc.</h5>
            </div>
        </div>*@

    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="fluid-container">

            <div class="content-wrapper">


                @RenderBody()



                <hr>

                <div class="row" id="footer">
                    <div class="col-md-12 text-center">
                        <p class="copyright-text">© DistlerFuchs / V 1.0.00</p>
                    </div>
                </div>

            </div>

        </div>
    </div>


    @*This renders scripts, which are called in views*@
    @RenderSection("Scripts", required: false)

</body>
</html>